#!/bin/bash
# Fix the ICU script after it's generated by xcodebuild

set -e

echo "Fixing ICU Python script..."

SCRIPT_FILE="_cache/mac/Release/minimal_icu_data.build/Script-2424BE3698E0986667A18F78.sh"

if [ -f "$SCRIPT_FILE" ]; then
    echo "Found script: $SCRIPT_FILE"
    
    # Replace 'exec python' with 'exec python2'
    sed -i '' 's/exec python /exec python2 /g' "$SCRIPT_FILE"
    
    echo "✓ Fixed script to use python2"
    echo "Script now contains:"
    head -3 "$SCRIPT_FILE"
else
    echo "Script not found yet (will be generated during build)"
fi
