<#
.SYNOPSIS
    Adds the MSVC v141 (VS 2017) toolset, its ATL and MFC libraries and a
    Windows SDK to an existing Visual Studio 2022 installation.

.DESCRIPTION
    The projects generated by config.py use PlatformToolset v141
    (config/win32.gypi) and link prebuilt libraries that were built with v141.
    The GitHub-hosted windows-2022 image has Visual Studio 2022 without the
    v141 toolset, so CI adds it with "vs_installer.exe modify". This takes
    about five minutes.

    The script finds Visual Studio with vswhere, runs the installer (a second
    time if the first run does not leave the toolset in place), and then checks
    that VC\Tools\MSVC\14.16.*, the v141 ATL/MFC headers and the Windows SDK
    are present. It exits non-zero if they are not.

    It can also be used on a developer machine from an elevated PowerShell
    prompt. Use -VerifyOnly to check an installation without changing it.

    When run under GitHub Actions it writes these step outputs:
        install-path         Visual Studio folder, with a trailing backslash
                             (the form make.cmd expects in VSINSTALLDIR)
        msvc-v141-version    for example 14.16.27023
        windows-sdk-version  for example 10.0.17763.0

.PARAMETER InstallPath
    Visual Studio installation to modify. Default: the newest Visual Studio
    2022 that vswhere reports with the x64 C++ tools installed.

.PARAMETER Components
    Visual Studio component IDs to add.

.PARAMETER WindowsSdkVersion
    Windows SDK version that must be installed afterwards.

.PARAMETER WindowsSdkComponent
    Component ID to add when that Windows SDK is missing.

.PARAMETER VersionRange
    vswhere version range used to pick the installation ([17.0,18.0) is
    Visual Studio 2022).

.PARAMETER MaxAttempts
    How many times to run the installer before giving up.

.PARAMETER LogDir
    Folder to copy the Visual Studio installer logs (%TEMP%\dd_*.log) into.

.PARAMETER VerifyOnly
    Only report what is installed; do not run the installer.
#>
[CmdletBinding()]
param(
    [string]$InstallPath,
    [string[]]$Components = @(
        'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
        'Microsoft.VisualStudio.Component.VC.v141.x86.x64',
        'Microsoft.VisualStudio.Component.VC.v141.ATL',
        'Microsoft.VisualStudio.Component.VC.v141.MFC'
    ),
    [string]$WindowsSdkVersion = '10.0.17763.0',
    [string]$WindowsSdkComponent = 'Microsoft.VisualStudio.Component.Windows10SDK.17763',
    [string]$VersionRange = '[17.0,18.0)',
    [ValidateRange(1, 5)]
    [int]$MaxAttempts = 2,
    [string]$LogDir,
    [switch]$VerifyOnly
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$InstallerDir = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer'
$VsWhere = Join-Path $InstallerDir 'vswhere.exe'
$VsInstaller = Join-Path $InstallerDir 'vs_installer.exe'
$SdkRoot = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10'

function Write-GitHubOutput([string]$Name, [string]$Value) {
    if ($env:GITHUB_OUTPUT) {
        $utf8 = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::AppendAllText($env:GITHUB_OUTPUT, "$Name=$Value`n", $utf8)
    }
}

function Find-VisualStudio {
    if (-not (Test-Path -LiteralPath $VsWhere)) {
        throw "vswhere.exe not found at $VsWhere. Install Visual Studio 2022 or its Build Tools first."
    }

    $common = @('-products', '*', '-latest', '-property', 'installationPath', '-nologo')
    $cxx = @('-requires', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64')

    # Prefer Visual Studio 2022 with the x64 C++ tools, then any Visual Studio
    # 2022, then any version: hosted images have been known to move labels to
    # newer Visual Studio releases, where the v141 component is still
    # installable.
    $searches = @(
        @{ Args = @('-version', $VersionRange) + $cxx; Note = '' },
        @{ Args = @('-version', $VersionRange); Note = "No Visual Studio in version range $VersionRange has the x64 C++ tools; they will be added." },
        @{ Args = @(); Note = "No Visual Studio in version range $VersionRange was found; using the newest installation." }
    )
    foreach ($search in $searches) {
        $searchArgs = $search.Args + $common
        $path = & $VsWhere @searchArgs
        if ($LASTEXITCODE -ne 0) { throw "vswhere failed with exit code $LASTEXITCODE" }
        if ($path) {
            if ($search.Note) { Write-Warning $search.Note }
            return ([string]@($path)[0]).Trim()
        }
    }
    throw 'vswhere found no Visual Studio installation. Install Visual Studio 2022 or the Visual Studio 2022 Build Tools first.'
}

# Returns what is currently installed: the v141 tools folder, ATL, MFC and the SDK
function Get-ToolsetState([string]$VsPath) {
    $state = [ordered]@{
        Vcvars      = $false
        V141Dir     = $null
        V141Version = $null
        Compiler    = $false
        Atl         = $false
        Mfc         = $false
        Sdk         = $false
    }

    # make.cmd sets up the build environment with vcvarsall.bat
    $state.Vcvars = Test-Path -LiteralPath (Join-Path $VsPath 'VC\Auxiliary\Build\vcvarsall.bat')

    $msvcRoot = Join-Path $VsPath 'VC\Tools\MSVC'
    if (Test-Path -LiteralPath $msvcRoot) {
        $dirs = @(Get-ChildItem -LiteralPath $msvcRoot -Directory |
                  Where-Object { $_.Name -like '14.16.*' } |
                  Sort-Object { [version]$_.Name } -Descending)
        if ($dirs.Count -gt 0) {
            $dir = $dirs[0].FullName
            $state.V141Dir = $dir
            $state.V141Version = $dirs[0].Name
            $state.Compiler = Test-Path -LiteralPath (Join-Path $dir 'bin\Hostx64\x64\cl.exe')
            $state.Atl = (Test-Path -LiteralPath (Join-Path $dir 'atlmfc\include\atlbase.h')) -and
                         (Test-Path -LiteralPath (Join-Path $dir 'atlmfc\lib\x64\atls.lib'))
            # revbrowser.rc includes afxres.h, which comes with the MFC component
            $state.Mfc = Test-Path -LiteralPath (Join-Path $dir 'atlmfc\include\afxres.h')
        }
    }

    $state.Sdk = (Test-Path -LiteralPath (Join-Path $SdkRoot "Include\$WindowsSdkVersion\um\windows.h")) -and
                 (Test-Path -LiteralPath (Join-Path $SdkRoot "Lib\$WindowsSdkVersion\um\x64\kernel32.lib"))

    return New-Object PSObject -Property $state
}

function Test-ToolsetComplete($State) {
    return ($State.Vcvars -and $State.V141Dir -and $State.Compiler -and $State.Atl -and $State.Mfc -and $State.Sdk)
}

function Show-ToolsetState($State) {
    $v141 = if ($State.V141Dir) { $State.V141Dir } else { '(missing)' }
    Write-Host "  vcvarsall.bat          : $($State.Vcvars)"
    Write-Host "  MSVC v141 tools folder : $v141"
    Write-Host "  v141 x64 compiler      : $($State.Compiler)"
    Write-Host "  v141 ATL (atlbase.h)   : $($State.Atl)"
    Write-Host "  v141 MFC (afxres.h)    : $($State.Mfc)"
    Write-Host "  Windows SDK $WindowsSdkVersion : $($State.Sdk)"
}

function Wait-InstallerProcesses([datetime]$Since) {
    # vs_installer.exe can hand work to other installer processes and exit
    # before they finish; wait until the ones started since $Since are gone.
    $deadline = (Get-Date).AddMinutes(20)
    while ((Get-Date) -lt $deadline) {
        $running = @(Get-Process -ErrorAction SilentlyContinue | Where-Object {
            $p = $null
            $t = $null
            try { $p = $_.Path; $t = $_.StartTime } catch { }
            $p -and $t -and $t -ge $Since -and
                $p.StartsWith($InstallerDir, [System.StringComparison]::OrdinalIgnoreCase) -and
                ($_.ProcessName -match '^(vs_installer|vs_installershell|setup|vs_setup_bootstrapper)$')
        })
        if ($running.Count -eq 0) { return }
        Start-Sleep -Seconds 5
    }
    Write-Warning 'Visual Studio installer processes are still running after 20 minutes.'
}

function Copy-InstallerLogs {
    if (-not $LogDir) { return }
    $tempDir = [System.IO.Path]::GetTempPath()
    $logs = @(Get-ChildItem -LiteralPath $tempDir -Filter 'dd_*.log' -File -ErrorAction SilentlyContinue)
    if ($logs.Count -eq 0) { return }
    New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
    foreach ($log in $logs) {
        Copy-Item -LiteralPath $log.FullName -Destination $LogDir -Force
    }
    Write-Host "Copied $($logs.Count) installer log(s) to $LogDir"
}

function Show-InstallerErrors {
    $tempDir = [System.IO.Path]::GetTempPath()
    $errorLog = Get-ChildItem -LiteralPath $tempDir -Filter 'dd_setup_*_errors.log' -File -ErrorAction SilentlyContinue |
                Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($errorLog -and $errorLog.Length -gt 0) {
        Write-Host "---- last lines of $($errorLog.FullName) ----"
        Get-Content -LiteralPath $errorLog.FullName -Tail 60 | ForEach-Object { Write-Host $_ }
        Write-Host '----'
    }
}

if ($InstallPath) {
    if (-not (Test-Path -LiteralPath $InstallPath -PathType Container)) { throw "Visual Studio folder not found: $InstallPath" }
    $vs = (Resolve-Path -LiteralPath $InstallPath).ProviderPath
}
else {
    $vs = Find-VisualStudio
}
$vs = $vs.TrimEnd('\')
$vsVersion = ''
if (Test-Path -LiteralPath $VsWhere) {
    $vsVersion = & $VsWhere -path $vs -property installationVersion -nologo
    $global:LASTEXITCODE = 0
}
Write-Host "Visual Studio: $vs (version $vsVersion)"

$state = Get-ToolsetState $vs
Write-Host 'Before:'
Show-ToolsetState $state

if (-not (Test-ToolsetComplete $state)) {
    if ($VerifyOnly) {
        throw 'The MSVC v141 toolset, its ATL/MFC libraries or the Windows SDK is missing (-VerifyOnly was given, so nothing was installed).'
    }
    if (-not (Test-Path -LiteralPath $VsInstaller)) {
        throw "vs_installer.exe not found at $VsInstaller"
    }

    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Warning 'Not running elevated; the Visual Studio installer needs administrator rights and may fail.'
    }

    $toAdd = @($Components)
    if (-not $state.Sdk) { $toAdd += $WindowsSdkComponent }

    # Start-Process joins an argument array without quoting, so build the
    # command line by hand. $vs has no trailing backslash, so the closing
    # quote is not escaped.
    $argLine = "modify --installPath `"$vs`""
    foreach ($c in $toAdd) { $argLine += " --add $c" }
    $argLine += ' --quiet --norestart --nocache'

    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        Write-Host "Attempt $attempt of ${MaxAttempts}: `"$VsInstaller`" $argLine"
        $started = Get-Date
        $proc = Start-Process -FilePath $VsInstaller -ArgumentList $argLine -Wait -PassThru -NoNewWindow
        Wait-InstallerProcesses $started
        $elapsed = [int]((Get-Date) - $started).TotalSeconds
        $code = $proc.ExitCode
        Write-Host "vs_installer exited with code $code after $elapsed s"
        if ($code -eq 3010) {
            Write-Warning 'The installer reports that a restart is required (3010); continuing.'
        }
        elseif ($code -ne 0) {
            Show-InstallerErrors
        }

        $state = Get-ToolsetState $vs
        if (Test-ToolsetComplete $state) { break }
        Write-Warning "Toolset still incomplete after attempt $attempt."
        Show-ToolsetState $state
    }

    Copy-InstallerLogs
}

Write-Host 'After:'
Show-ToolsetState $state

if (-not (Test-ToolsetComplete $state)) {
    throw "Visual Studio at $vs still lacks the MSVC v141 toolset (VC\Tools\MSVC\14.16.*), its ATL/MFC files or Windows SDK $WindowsSdkVersion."
}

Write-GitHubOutput 'install-path' "$vs\"
Write-GitHubOutput 'msvc-v141-version' $state.V141Version
Write-GitHubOutput 'windows-sdk-version' $WindowsSdkVersion
Write-Host "OK: MSVC $($state.V141Version) (v141) with ATL/MFC and Windows SDK $WindowsSdkVersion in $vs"
